config/routes.rb
Rails.application.routes.draw do
  resources :trips
  put '/book/:id', to: 'trips#book_seat', as: :book_seat
  put '/unbook/:id', to: 'trips#unbook_seat', as: :unbook_seat
  put '/clear/:id', to: 'trips#clear', as: :clear_trip
  get '/find-a-trip', to: 'trips#find', as: :find_trip
  post '/search', to: 'trips#search', as: :search_trip
  get '/destinations', to: 'trips#destinations', as: :destinations
  root to: 'trips#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id           :integer          not null, primary key
#  price        :float
#  origin       :string
#  destination  :string
#  seats        :integer
#  booked_seats :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Trip < ApplicationRecord

  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :origin, presence: true
  validates :destination, presence: true
  validates :seats, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :booked_seats, numericality: { greater_than_or_equal_to: 0 }

  def full?
    seats == booked_seats
  end

  def available_seats
    seats - booked_seats
  end

  def price_formatted
    "#{sprintf('%.2f', price)} €"
  end

  def book
    self.booked_seats = self.booked_seats < self.seats ? self.booked_seats + 1 : self.booked_seats
  end

  def unbook
    self.booked_seats = self.booked_seats > 0 ? self.booked_seats - 1 : self.booked_seats
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  def index
    @trips = nil
  end

  def show
    @trip = nil
  end

  def new
    @trip = nil
  end

  def edit
    @trip = nil
  end

  def create
    @trip = nil
    @trip.save
  end

  def update
    @trip = nil
    @trip.update(params[:trip])
  end

  def destroy
    @trip = nil
    @trip.destroy
  end

  def book_seat
  end

  def unbook_seat
  end

  def clear
  end

  def find
  end

  def search
  end

  def destinations
    @destinations = Trip.distinct.pluck(:destination)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
        when "notice" then "alert alert-info alert-dismissible fade show"
        when "success" then "alert alert-success alert-dismissible fade show"
        when "error" then "alert alert-danger alert-dismissible fade show"
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
  def origins_for_select
    options_for_select(Trip.distinct.pluck(:origin))
  end

  def destinations_for_select
    options_for_select(Trip.distinct.pluck(:destination))
  end
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  %p{class: flash_class(key), role: "alert"}
    = value
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} &times;

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand.navbar-light.bg-light
  = link_to 'Trips manager', root_path, class: 'navbar-brand'
  %button.navbar-toggler{type: "button", "data-toggle": "collapse", "data-target": "#navbarNav", "aria-controls": "navbarNav", "aria-expanded": "false", "aria-label": "Toggle navigation"}
    %span.navbar-toggler-icon
  .collapse.navbar-collapse#navbarNav
    %ul.navbar-nav
      %li.navbar-item
        = link_to 'All trips', trips_path, class: "nav-link"
      %li.navbar-item
        = link_to 'Find a trip', find_trip_path, class: "nav-link"
      %li.navbar-item
        = link_to 'Destinations', destinations_path, class: "nav-link"
  = link_to 'New trip', new_trip_path, class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, user-scalable=no", :name => "viewport"}/
    %title ControllerExercises
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container-fluid
      = yield

app/views/trips/_form.html.haml
= form_for @trip do |f|
  - if @trip.errors.any?
    .alert.alert-danger
      %h2= "#{pluralize(@trip.errors.count, "error")} prohibited this trip from being saved:"
      %ul
        - @trip.errors.full_messages.each do |message|
          %li= message

  .form-group
    = f.text_field :price, placeholder: :price, class: "form-control", autocomplete: "off"
  .form-group
    = f.text_field :origin, placeholder: :origin, class: "form-control", autocomplete: "off"
  .form-group
    = f.text_field :destination, placeholder: :destination, class: "form-control", autocomplete: "off"
  .form-group
    = f.number_field :seats, placeholder: :seats, class: "form-control", autocomplete: "off"
  .form-group
    = f.submit 'Save', class: "btn btn-success"
    = link_to 'Cancel', trips_path, class: "btn btn-danger"

app/views/trips/create.html.haml
- if @trip.errors.any?
  .alert.alert-danger
    %h2= "#{pluralize(@trip.errors.count, "error")}:"
    %ul
      - @trip.errors.full_messages.each do |message|
        %li= message
    = link_to 'Try again', new_trip_path
- else
  .alert.alert-info
    The trip was successfully created
    = link_to 'See trip', @trip

app/views/trips/destinations.html.haml
%h1.text-center.mb-4.mt-4 Destination list

- if @destinations.blank?
  .alert.alert-info There are no trips yet
- else
  .row
    .col-12.col-md-6.offset-md-3
      .list-group
        - @destinations.each do |destination|
          = link_to destination, trips_path(destination: destination), class: "list-group-item list-group-item-action"

app/views/trips/destroy.html.haml
.alert.alert-info
  The trip was successfully destroyed
  = link_to 'See pages trip', trips_path

app/views/trips/edit.html.haml
%h1.text-center Editing trip
.row
  .col-12.col-md-6.offset-md-3
    = render 'form'

app/views/trips/find.html.haml
%h1.text-center.mt-4 Find a trip
%h3.text-center.mb-4 Where do you want to travel?
- if Trip.count == 0
  .alert.alert-info
    There are no trips available
- else
  = form_tag search_trip_path do
    .row
      .col-12.col-md-4.offset-md-1.form-group
        = label_tag "Origin"
        = select_tag "origin", origins_for_select, class: "form-control"
      .col-12.col-md-4.form-group
        = label_tag "Destination"
        = select_tag "destination", destinations_for_select, class: "form-control"
      .col-12.col-md-2
        = submit_tag "Find my trip", class: "btn btn-primary"

app/views/trips/index.html.haml
%h1.text-center.mb-4.mt-4
  - if @destination
    Trips to
    = @destination
  - else
    All trips

- if @trips.blank?
  .alert.alert-info
    There are no trips yet
- else
  .row
    .col-12.col-md-8.offset-md-2
      %table.table.table-hover.table-borderless
        %thead
          %tr
            %th{scope: "col"} Origin
            %th{scope: "col"} Destination
            %th{scope: "col"} Price
            %th{scope: "col"} Available seats
            %th{scope: "col"} Actions
        %tbody
          - @trips.each do |trip|
            %tr{class: trip.full? ? "table-danger" : "table-success"}
              %td=trip.origin
              %td=trip.destination
              %td=trip.price_formatted
              %td=trip.seats - trip.booked_seats
              %td
                = link_to 'Details', trip
                |
                = link_to 'Edit', edit_trip_path(trip)
                |
                = link_to 'Delete', trip, method: 'delete'
                |
                = link_to 'Clear', clear_trip_path(trip), method: 'put'

app/views/trips/new.html.haml
%h1.text-center New trip
.row
  .col-12.col-md-6.offset-md-3
    = render 'form'

app/views/trips/search.html.haml
%h1.text-center.mt-4.mb-4="Trips from #{@origin} to #{@destination}"
= link_to 'New search', find_trip_path, class: "btn btn-success"
- if @trips.blank?
  .alert.alert-danger
    There were no results for this search
- else
  .row
    .col-12.col-md-8.offset-md-2
      %table.table.table-hover.table-borderless
        %thead
          %tr
            %th{scope: "col"} Origin
            %th{scope: "col"} Destination
            %th{scope: "col"} Price
            %th{scope: "col"} Available seats
            %th{scope: "col"} Book a seat
        %tbody
          - @trips.each do |trip|
            %tr{class: trip.full? ? "table-danger" : "table-success"}
              %td=trip.origin
              %td=trip.destination
              %td=trip.price_formatted
              %td=trip.seats - trip.booked_seats
              %td
                - if trip.full?
                  %small.text-muted No seats available
                - else
                  = link_to 'Book', book_seat_path(trip), class: "btn btn-primary"

app/views/trips/show.html.haml
%h1.text-center.mb-4.mt-4="Trip from #{@trip.origin} to #{@trip.destination}"

.row
  .col-12.col-md-5.offset-md-1
    .card
      .card-header
        %h3 Trip details
      .card-body
        %table.table.table-borderless
          %tbody
            %tr
              %th{scope: "row"} Origin
              %td=@trip.origin
            %tr
              %th{scope: "row"} Destination
              %td=@trip.destination
            %tr
              %th{scope: "row"} Price
              %td=@trip.price_formatted
            %tr
              %th{scope: "row"} Total seats
              %td=@trip.seats
            %tr
              %th{scope: "row"} Available seats
              %td=@trip.available_seats
      .card-footer
        = link_to 'Edit', edit_trip_path(@trip), class: 'card-link'
        = link_to 'Delete', @trip, method: 'delete', class: 'card-link'
        = link_to 'Clear', clear_trip_path(@trip), method: 'put', class: 'card-link'
  .col-12.col-md-5
    .card
      .card-header
        %h3 Seats map
      .card-body
        - @trip.seats.times do |seat|
          - if seat % 5 == 0
            %br
          = link_to '', seat < @trip.available_seats ? book_seat_path(@trip) : unbook_seat_path(@trip), class: seat < @trip.available_seats ? "btn btn-success" : "btn btn-danger", method: 'put'

app/views/trips/update.html.haml
- if @trip.errors.any?
  .alert.alert-danger
    %h2= "#{pluralize(@trip.errors.count, "error")}:"
    %ul
      - @trip.errors.full_messages.each do |message|
        %li= message
    = link_to 'Try again', edit_trip_path(@trip)
- else
  .alert.alert-info
    The trip was successfully updated
    = link_to 'See trip', @trip